### ISSUE TITLE
Suggestion - desktop version using Electron

### ISSUE THREAD

**Issue by paulbjensen** [elendirx/web2web#10]
Hi,

I created a desktop version of this repo using Electron to serve up the index.html file, the repo and branch url is here: https://github.com/paulbjensen/web2web/tree/desktop.

Would you be interested in a web2web-desktop version as a separate repo alongside this repo?

**Comment by elendirx** [comment]
Man I like your code. I didn't even know this was possible. It's amazing how easy it is to create a desktop app with electron! I don't want to create another repo though as I'd like to keep web2web browser-only at the moment.
