### ISSUE TITLE
live demo stuck on Loading

### ISSUE THREAD

**Issue by ackvf** [elendirx/web2web#14]
![image](https://user-images.githubusercontent.com/2313018/58562286-3ff80680-8229-11e9-877f-172baea25d9c.png)
Nothing happens after a minute or two.

There is also an error contacting the blockexplorer api
![image](https://user-images.githubusercontent.com/2313018/58562414-7c2b6700-8229-11e9-95db-7d0d19bc877c.png)

**Comment by elendirx** [comment]
Please see https://github.com/elendirx/web2web/issues/15#issuecomment-502591525
