### ISSUE TITLE
Ethereum blockchain

### ISSUE THREAD

**Issue by eduardonunesp** [elendirx/web2web#2]
Why not leverage the Ethereum as well, and you'll receive a Virtual Machine and Smart Contracts for free

**Comment by elendirx** [comment]
Thanks for the idea! I'm not familiar with most of the altcoins, but didn't etherum suffer from some serious attack recently?

**Comment by eduardonunesp** [comment]
AFAIK the attack happened because there's a fail in the Smart Contract programming for the DAO, so the attacker was able to blow up the contract.

**Comment by rstormsf** [comment]
The attack had nothing to do with Ethereum itself. The attack was executed on a smart contract DAO which led to an idea of hard fork which led to 2 projects: Ethereum and Ethereum Classic(those who didn't want to update to hard fork). Anyways, you can safely use ethereum platform, but keep in mind once you publish a contract you can't easily change/fix bugs after. Hence why DAO got into this problem. There was a bug in it and it couldn't be fixed.

**Comment by eduardonunesp** [comment]
👏  exactly @rstormsf, regarding the contract programming there's ways to programming contracts which scales and easily to update.
