### ISSUE TITLE
Register the DNS on namecoin

### ISSUE THREAD

**Issue by eduardonunesp** [elendirx/web2web#3]
https://namecoin.org/

**Comment by rstormsf** [comment]
If you do register it, you have to keep your private key from your domain. If you lose it, you lose control of your domain. Plus, you will need NXT coins in order to pay, hence you will need to get it from exchange, hence you need to acquire bitcoin, etc.

**Comment by elendirx** [comment]
I really like namecoin. The thing is, I'm looking for a solution where the common user ideally doesn't have to use anything else but the browser. As far as I know one must install software to browse namecoin websites.

**Comment by eduardonunesp** [comment]
I'm not sure, a service like https://bit.no.com/ or https://bit.namecoin.info/ can be an option

**Comment by kapouer** [comment]
Would it be possible to work out a javascript DNS resolver using web workers ? Imagine the possibilities...

**Comment by elendirx** [comment]
@eduardonunesp Thanks for the links, I didn't know there were free namecoin proxies.
@kapouer Could you please elaborate on the idea?

**Comment by kapouer** [comment]
I read it was possible to handle 404 errors using a service worker. (http://www.html5rocks.com/en/tutorials/service-worker/introduction/). Maybe it is possible to handle other network errors, like a DNS failure, and hook into it to resolve the domain name using a different protocol (like namecoin), thus giving the user transparent access to a completely decentralized internet...

**Comment by elendirx** [comment]
Interesting idea. I don't know much about service workers, but I think they require https which would indicate that they are available only after you've connected to a server.
