### ISSUE TITLE
How to host a full-scale website?

### ISSUE THREAD

**Issue by gigix** [elendirx/web2web#5]
I assume some website owners/editors are looking for a solution which allows:
1. web pages being linked to each other through relative addresses (e.g. `<a href='another.html'>see more</a>`) without involving blockchain or magnet.
2. similarly, assets (javascripts, images, stylesheets, etc.) being linked through relative addresses.
3. infrastructural utilities/scripts to initialise/publish/update a whole website.

Is there any plan or design yet?

**Comment by elendirx** [comment]
Yes, I too think that these should be the next steps. 1 & 2 are possible and people have done that - take a look at [peerweb](https://github.com/retrohacker/peerweb.js). 3 is something I'd like to see if only for the sake of saving my own time while experimenting. There's no timeline though.

**Comment by eduardonunesp** [comment]
1 - You can achieve that with SPA applications, when everything are contained in a single bundle, see: webpack

2 - It's possible to create another bundle with assets, it can be embed or distributed in bundles of images, which can be used by many projects at the same time

3 - Trick point, due the technology still relatively new, there are many tools and ideas which can be leverage, but it's needs a work to create sort of "framework" to make the development task easier

**Comment by gigix** [comment]
Had a look around. As @elendirx said, peerweb seems to be an interesting approach - you can always wrap a complete website as one single torrent file, then use the same blockchain mechanism as version tracking. 

It might make sense to check the progress of [Maelstrom](https://www.sitepoint.com/bittorrents-maelstrom-using-torrents-host-websites/). I reckon the downside of Maelstrom is it requires a new browser. But might be valuable to learn how they support website owners.

**Comment by eduardonunesp** [comment]
Requires to download a new browser is a little intrusive, we don't want to change too much to using torrent base site, maybe an extension can help a lot

**Comment by fogoat** [comment]
@gigix Maelstrom doesn't work very well. The torrents they use have very basic structure and even then the response time is very slow. Bittorrent is not a good base for serving specific files. There is a [Bittorrent Enhancement Proposal 47 - Padding files and extended file attributes](http://www.bittorrent.org/beps/bep_0047.html) that may help retrieve files faster by aligning files along torrent piece boundaries. Unfortunately, this is a DRAFT and who knows when it will be adopted if ever. 

I think [webseeding ](http://www.bittorrent.org/beps/bep_0019.html) in torrent should be considered as a backup, leveraging some sort of [persistent URL](https://blog.archive.org/2016/09/27/persistent-url-service-purl-org-now-run-by-the-internet-archive/) within webseeding.
