### ISSUE TITLE
You should first check to see from where OP_RETURN was received.

### ISSUE THREAD

**Issue by Coding-Enthusiast** [elendirx/web2web#8]
Since anybody can create a TX with `OP_RETURN` and send to `CONFIG.btcAddress` you should check to make sure it was sent from `CONFIG.btcAddress` and not another address. If not checked anybody can insert a new torrent hash.

Do this by checking the following:

```
for (var k = 0; k < data.txs[i].vin.length; j++) {
    if(data.tx[i].vin[k].addr == CONFIG.btcAddress)
```

**Comment by elendirx** [comment]
You're right. Thanks for your help! I fixed it in https://github.com/elendirx/web2web/commit/ed97e2574ca29eeec76fff42479bb8c54a6a4bc5.
