### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DarrenRainey** [elendirx/web2web#9]
You might want to look at something like hive mind which is a decentralized storage solution by saving data in java script and cookies on visitors machines so if you get enough traffic it would be almost impossible to take it down

**Comment by elendirx** [comment]
Thanks for the tip! In case anyone else is interested, here's the link: https://github.com/seantmalone/HiveMind.

**Comment by DarrenRainey** [comment]
im currently working on a similar project that saves the websites code to cookies to speed up connection times as the first time it will download the webpage save it as a cookie then load it but after that the website can be decoded and loaded from the users cookie saving on bandwidth and also making a backup of the site in the event the site is taken offline just need to figure out  a way of having it update the users cookie when the website changes

**Comment by Tedko** [comment]
Hi Darren! How’s the status of your project? We’re building sth upon similar layer of web2web.

**Comment by DarrenRainey** [comment]
Honestly I haven't work on it in years but I might dig up some of the code and work on it again at some point.

**Comment by Tedko** [comment]
cool. Looking forward. Checkout https://maskbook.com if you have time.
